### ** EXAMPLE tidy_raccoons.rds

## vignettes/tidy_raccoons.rds : generates tidy raccoon dataset
vignettes/tidy_raccoons.rds: data-raw/raccoons.csv vignettes/010_tidying_data.Rmd
	@Rscript -e 'library(rmarkdown); render("vignettes/010_tidying_data.Rmd")'
	@rm -f vignettes/010_tidying_data.pdf
	@rm -f vignettes/010_tidying_data.tex


### ** EXAMPLE 2 Analyses.pdf

## vignettes/Analyses.pdf : knit a pdf of my anaylses using the latest data
vignettes/Analyses.pdf: vignettes/tidy_raccoons.rds vignettes/020_running_analyses.Rmd
	@Rscript -e 'library(rmarkdown); render("vignettes/020_running_analyses.Rmd", output_format = pdf_document(), output_file = "Analyses.pdf")'

### ** pkgdown

## pkgdown : build the package site using pkgdown
.PHONY: pkgdown
pkgdown:
	@printf "\n"
	@printf "*** Building package website with pkgdown ***\n"
	@printf "\n"
	@Rscript -e 'library(pkgdown); build_site()'






### ** help
# https://swcarpentry.github.io/make-novice/08-self-doc/index.html
.PHONY: help
help: Makefile
	@printf "\n"
	@printf "Please use 'make <target>' where <target> is one of\n"
	@printf "\n"
	@sed -n 's/^## /    /p' $<




###	** pdfs

## pdfs : knits vignettes in vignettes folder as pdf
.PHONY:	pdfs
pdfs:
	@printf	"\n"
	@printf	"*** Knitting vignettes into pdf files ***\n"
	@printf	"\n"
	@Rscript	R/knit_pdfs.R





### ** clean-man

## clean-man : delete documentation generated by Roxygen
.PHONY: clean-man
clean-man:
	rm -f man/*

### ** clean-docs

## clean-docs : delete documentation generated by pkgdown
.PHONY: clean-docs
clean-docs:
	rm -fr docs/

### ** clean-pfd

## clean-pdf : delete folder containing knitted vignettes
.PHONY: clean-pdf
clean-pdf:
		rm -fr pdf/

### ** clean-vignettes

## clean-vignettes : remove html, rda and rds files from the vignettes/ folder
.PHONY: clean-vignettes
clean-vignettes:
	@printf "\n"
	@printf "*** Cleaning vignettes/ folder ***\n"
	@printf "\n"
	rm -f vignettes/*.rds
	rm -f vignettes/*.csv
	rm -f vignettes/*.html
	rm -f vignettes/*.pdf
	rm -f vignettes/*.tex

### ** clean_all

## clean_all : delete all files and folders generated during building process
.PHONY: clean_all
clean_all: clean-man clean-docs clean-vignettes clean-pdf
	@printf "\n"
	@printf "*** Cleaned generated files and folders ***\n"
	@printf "\n"

