---
title: "vitisSpread_maxent_gbif_retrieval2022 (slfrsk_practice_step-1-3)"
author: "Sam Owens"
date: '2022-07-07'
contact: 'sam.owens@temple.edu'
output: html_document
---

File paths edited 2023-06-01

```{r load necesssary packages, echo = FALSE}

# install.packages("devtools")
# install.packages("htmltools")

library(cli)
library(devtools)

# install_github("ieco-lab/slfrsk")

library(slfrsk) #this package, has extract_enm()
library(tidyverse)  #data manipulation

library(here) #making directory pathways easier on different instances
here()
# here() is "C:/Users/tun83449/OneDrive - Temple University/Shared drives/slfClimate/projects/slfSpread/slfSpread_pkg"

library(spocc) #query gbif and format as a dataframe (most important)
library(scrubr) #clean records for gbif data
library(humboldt) #rarefy points
library(tcltk) #humboldt progress bar
library(patchwork) #easy combined plots
library(taxize) # get species IDs from databases

```

# Acquire Data

```{r gbif queries}

# get species ID from gbif database
ids <- get_ids(sci_com = "Vitis", db = "gbif")

# ID = 7467468

# gbif queries with limits of 10^5- it is passed to occ_data in rgbif
vitis_gbif <- occ(ids = ids[[1]],
                  # search by ID, not species name
                  query = 'Vitis',
                  from = 'gbif', 
                  limit = 1e5, 
                  has_coords = TRUE, 
                  throw_warnings = TRUE,
                  # list of commands to pass to rgbif
                  gbifopts = list(hasCoordinate = TRUE,
                                  occurrenceStatus = "PRESENT",
                                  # all records except fossil records
                                  basisOfRecord = c("HUMAN_OBSERVATION", "MATERIAL_CITATION", "MATERIAL_SAMPLE", "LIVING_SPECIMEN", "MACHINE_OBSERVATION", "OBSERVATION", "PRESERVED_SPECIMEN", "OCCURRENCE"),
                                  hasGeospatialIssue = FALSE,
                                  # verbatimScientificName = "Vitis L",
                                  year = "1970, 2022"
                             ))
  
```

```{r data frame setup and cleaning}
  
  # tibble raw queries
vitis_gbif_final <- as_tibble(vitis_gbif$gbif$data$`7467468`) 

  # save raw queries with date stamp as current date
write_csv(x = vitis_gbif_final, 
          file = file.path(here(), "data_raw", paste0( "vitis_spp_gbif_", format(Sys.Date(), "%Y-%d-%m"), ".csv")))
  
  # convert occ data to dataframe
vitis_coords1 <- occ2df(vitis_gbif)
  
  # save coords as-is
write_csv(x = vitis_coords1, 
          file = file.path(
            here(), "data_raw", 
            paste0( "vitis_gbif_raw_coords_", format(Sys.Date(), "%Y-%d-%m"), ".csv"))
          )

```

```{r read in raw data and clean}

vitis_coords1 <- read_csv(file = file.path(here(), "data_raw", "vitis_gbif_raw_coords_2023-14-02.csv"))

# make taxonomic naming consistent
unique(vitis_coords1$name)

# coordinate veracity
vitis_coords1 <- vitis_coords1 %>%
  coord_incomplete() %>%
  coord_impossible() %>%
  coord_unlikely()

```

```{r coordinate rarefication}

#rarefy (adjusts for differences in library sizes: selects a number of samples per group equal to smallest group size)
vitis_coords2 <- humboldt.occ.rarefy(in.pts = vitis_coords1, colxy = 2:3, rarefy.dist = 10, rarefy.units = "km", run.silent.rar = F)

#dedup
vitis_coords3 <- vitis_coords2 %>%
  dedup(how = "one", tolerance = 0.99)

vitis_coords3 <- vitis_coords3 %>%
  dplyr::select(name, latitude, longitude, prov, date, key) %>%
  # here down was cleaned using script cpnvert_data_rda.R- data table wont be converted to RDA file
  dplyr::rename(species = name, x = longitude, y = latitude) %>%
  mutate(species = "Vitis spp") %>%
  dplyr::select(species, x, y)

```  

```{r write data to .csv}

write_csv(vitis_coords3, file = file.path(here(), "data_root", "vitis_gbif_cleaned_coords_2022.csv"))

```

```{r output to be used for modeling and conversion to .csv}

vitis_points_cleaned <- vitis_coords3 %>%
  dplyr::rename(species = name, x = longitude, y = latitude) %>%
  mutate(species = "Lycorma delicatula") %>%
  dplyr::select(species, x, y)

write_csv(vitis_points_cleaned, file = file.path(here(), "data_root", "vitis_points_cleaned.csv"))

```

# Next chunk added 2022-11-21- to remove points that maxent was throwing errors for

```{r }

vitis_coords4 <- read_csv(file = file.path(here(), "data_root", "vitis_gbif_cleaned_v0.csv"))

# plot error points
map_errors <- ggplot() +
  geom_polygon(data = map_data('world'), aes(x = long, y = lat, group = group), fill = NA, color = "black", lwd = 0.15) +
  geom_point(data = vitis_error_points, aes(x = x, y = y), color = "red", size = 2) +
  coord_quickmap(xlim = c(-164.5, 163.5), ylim = c(-55, 85)) +
  ggtitle("vitis errors") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  theme_bw()

# all points are real (I was concerned that a - sign may have been missed), so these points will need to be removed

write_csv(vitis_coords4, file = file.path(here(), "data_root", "vitis_gbif_cleaned_v1.csv"))

```


```{r visualize 2022 pulled gbif records vs 2020 pull}

vitis_coords3 <- read_csv(file = file.path(here(), "data_root", "data_old", "vitis_gbif_cleaned_coords_2022.csv"))

data("vitis_points", package = "vitisrsk")
# we read in slightly modified versions of the same coords. lat/lon were changed to y/x respectively and the species names were cleaned up. see corresponding section in data-raw/convert_data_rda.R for details

# plot vitis
map_vitis <- ggplot() +
  geom_polygon(data = map_data('world'), aes(x = long, y = lat, group = group), fill = NA, color = "black", lwd = 0.15) +
  geom_point(data = vitis_coords3, aes(x = longitude, y = latitude), color = "red", size = 2) +
  geom_point(data = vitis_points, aes(x = x, y = y), color = "blue", shape = 2) +
  coord_quickmap(xlim = c(-164.5, 163.5), ylim = c(-55, 85)) +
  ggtitle("vitis") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  theme_bw()
  
```






