---
title: "Format risk tables for SLF populations and viticultural regions"
author: "Samuel M. Owens"
contact: "sam.owens@temple.edu"
date: "2024-05-07"
output: html_document
---

# Overview


(THEORY)

# Setup

```{r load necesssary packages, echo = FALSE}

# general tools
library(tidyverse)  #data manipulation
library(here) #making directory pathways easier on different instances
here::here() # here() starts at the root folder of this package.
library(devtools)

# table aesthetics
library(scales)
library(patchwork)
library(grid)
library(formattable)
library(kableExtra)

```

# IVR risk table

```{r read in table}

IVR_risk_table <- read.csv(file = file.path(here::here(), "vignette-outputs", "data-tables", "IVR_risk_table_global_regional_ensemble.csv"), row.names = 1)

```

```{r calculate percentages}

total_IVR <- sum(IVR_risk_table[1:4, 1:4])

IVR_shift_prop_table <- tibble(
  risk_shift = c("no_shift", "risk_increase", "risk_decrease"),
  prop_change = c(
    sum(IVR_risk_table[1, 1], IVR_risk_table[2, 2], IVR_risk_table[3, 3], IVR_risk_table[4, 4]) / total_IVR,
    sum(IVR_risk_table[2:4, 1], IVR_risk_table[3:4, 2], IVR_risk_table[4, 3]) / total_IVR,
    sum(IVR_risk_table[1, 2], IVR_risk_table[1:2, 3], IVR_risk_table[1:3, 4]) / total_IVR
  )
)

```


```{r format table}

IVR_risk_table[1:4, 1] <- formattable::proportion_bar("darkred")(IVR_risk_table[1:4, 1])
IVR_risk_table[1:4, 2] <- formattable::proportion_bar("darkorange")(IVR_risk_table[1:4, 2])
IVR_risk_table[1:4, 3] <- formattable::proportion_bar("gold")(IVR_risk_table[1:4, 3])
IVR_risk_table[1:4, 4] <- formattable::proportion_bar("gray")(IVR_risk_table[1:4, 4])

# print table, e.g., in html format
IVR_risk_table <- kable(IVR_risk_table, "html", escape = FALSE) %>% 
  kable_styling(bootstrap_options = "striped", full_width = FALSE) %>%
  # standardize col width
  kableExtra::column_spec(1:5, width_min = '4cm') %>%
  add_header_above(., header = c("Risk of L delicatula establishment in globally important viticultural regions" = 6), bold = TRUE)

  
```

```{r save table from above, if desired}

if(TRUE) {
  
  # save as .html
  kableExtra::save_kable(
    IVR_risk_table, 
    file = file.path(here::here(), "vignette-outputs", "figures", "IVR_risk_table_global_regional_ensemble.html"),
    self_contained = TRUE
    )
  
  # initialize webshot by 
 # webshot::install_phantomjs()
  # convert to pdf
  webshot2::webshot(
    url = file.path(here::here(), "vignette-outputs", "figures", "IVR_risk_table_global_regional_ensemble.html"),
    file = file.path(here::here(), "vignette-outputs", "figures", "IVR_risk_table_global_regional_ensemble.png")
  )
    
}

```

# SLF risk table

```{r read in table}

slf_risk_table <- read.csv(file = file.path(here::here(), "vignette-outputs", "data-tables", "slf_populations_risk_table_global_regional_ensemble.csv"), row.names = 1)

```

```{r calculate percentages}

total_slf <- sum(slf_risk_table[1:4, 1:4])

slf_shift_prop_table <- tibble(
  risk_shift = c("no_shift", "risk_increase", "risk_decrease"),
  prop_change = c(
    sum(slf_risk_table[1, 1], slf_risk_table[2, 2], slf_risk_table[3, 3], slf_risk_table[4, 4]) / total_slf,
    sum(slf_risk_table[2:4, 1], slf_risk_table[3:4, 2], slf_risk_table[4, 3]) / total_slf,
    sum(slf_risk_table[1, 2], slf_risk_table[1:2, 3], slf_risk_table[1:3, 4]) / total_slf
  )
)

```

```{r format table}

slf_risk_table[1:4, 1] <- formattable::proportion_bar("darkred")(slf_risk_table[1:4, 1])
slf_risk_table[1:4, 2] <- formattable::proportion_bar("darkorange")(slf_risk_table[1:4, 2])
slf_risk_table[1:4, 3] <- formattable::proportion_bar("gold")(slf_risk_table[1:4, 3])
slf_risk_table[1:4, 4] <- formattable::proportion_bar("gray")(slf_risk_table[1:4, 4])

# print table, e.g., in html format
slf_risk_table <- kable(slf_risk_table, "html", escape = FALSE) %>% 
  kable_styling(bootstrap_options = "striped", full_width = FALSE) %>%
  # standardize col width
  kableExtra::column_spec(1:5, width_min = '4cm') %>%
  add_header_above(., header = c("Risk of persistence for known L delicatula populations" = 6), bold = TRUE)

  
```


```{r save table from above, if desired}

if(TRUE) {
  
  # save as .html
  kableExtra::save_kable(
    slf_risk_table, 
    file = file.path(here::here(), "vignette-outputs", "figures", "slf_populations_risk_table_global_regional_ensemble.html"),
    self_contained = TRUE
    )
  
  # initialize webshot by 
 # webshot::install_phantomjs()
  # convert to pdf
  webshot2::webshot(
    url = file.path(here::here(), "vignette-outputs", "figures", "slf_populations_risk_table_global_regional_ensemble.html"),
    file = file.path(here::here(), "vignette-outputs", "figures", "slf_populations_risk_table_global_regional_ensemble.png")
  )
    
}

```

