---
title: "Plot AUC curves, variable contribution graphs and jackknife plots"
author: "Samuel M. Owens"
contact: "sam.owens@temple.edu"
date: "2024-08-16"
---

THEORY

# Setup

```{r load necesssary packages, echo = FALSE}

# general tools
library(tidyverse)  #data manipulation
library(here) #making directory pathways easier on different instances
here::here() # here::here() starts at the root folder of this package.
library(devtools)

# SDMtune and dependencies
library(SDMtune) # main package used to run SDMs
library(dismo) # package underneath SDMtune
library(rJava) # for running MaxEnt
library(plotROC) # plots ROCs

# aesthetics
#remotes::install_github("coolbutuseless/ggpattern")
library(ggpattern)

```

These plots depict the activity of the variables put into the MaxEnt models. I will create a combined figure for the 3 models in the regional_ensemble

```{r set wd}

mypath <- file.path(here::here() %>% 
                       dirname(),
                     "maxent/models")

```

```{r style object}

ensemble_colors <- c(
  "Rn (native)" = "#4daf4a",
  "Ri.NAmerica" =  "#e41a1c",
  "Ri.Asia" = "#377eb8"
)

```

```{r load model objects}

regional_native_model <- read_rds(file = file.path(mypath, "slf_regional_native_v3", "regional_native_model.rds"))

regional_invaded_model <- read_rds(file = file.path(mypath, "slf_regional_invaded_v7", "regional_invaded_model.rds"))

regional_invaded_asian_model <- read_rds(file = file.path(mypath, "slf_regional_invaded_asian_v2", "regional_invaded_asian_model.rds"))

```

```{r load testing objects}

regional_native_test <- read_rds(file = file.path(mypath, "slf_regional_native_v3", "regional_native_test.rds"))

regional_invaded_test <- read_rds(file = file.path(mypath, "slf_regional_invaded_v7", "regional_invaded_test.rds"))

regional_invaded_asian_test <- read_rds(file = file.path(mypath, "slf_regional_invaded_asian_v2", "regional_invaded_asian_test.rds"))

```

# ROC regional ensemble

```{r plot ROC per model}

regional_native_ROC <- SDMtune::plotROC(
  model = regional_native_model,
  test = regional_native_test
) %>%
  ggplot_build()


regional_invaded_ROC <- SDMtune::plotROC(
  model = regional_invaded_model,
  test = regional_invaded_test
) %>%
  ggplot_build()

regional_invaded_asian_ROC <- SDMtune::plotROC(
  model = regional_invaded_asian_model,
  test = regional_invaded_asian_test
) %>%
  ggplot_build()
           

```

```{r ROC plot}

ROC_ensemble <- ggplot() +
  # native model data
  geom_line(data = regional_native_ROC$data[[1]], aes(x = x, y = y, color = "Rn (native)", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # invaded model data
  geom_line(data = regional_invaded_ROC$data[[1]], aes(x = x, y = y, color = "Ri.NAmerica", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # invaded_asian model data
  geom_line(data = regional_invaded_asian_ROC$data[[1]], aes(x = x, y = y, color = "Ri.Asia", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # midpoint line
  geom_abline(slope = 1, linetype = "dashed") +
  # scales
  scale_x_continuous(name = "False positive rate (1 - specificity)", breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  scale_y_continuous(name = "True positive rate (sensitivity)", breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  labs(
    title = "ROC curve (true vs false positive rate) for 'regional_ensemble' models"
    ) +
  theme_bw() +
  # aes
  scale_color_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "color"
  ) +
  scale_linetype_manual(
    name = "Data segment",
    values = c("solid", "dotted"),
    labels = c("Test", "Train"),
    guide = guide_legend(reverse = TRUE)
  ) +
  theme(legend.position = "bottom") +
  coord_fixed(ratio = 1)

```

```{r save plot}

ggsave(
  ROC_ensemble, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "ROC_plot_regional_ensemble.jpg"
    ),
  height = 8, 
  width = 8,
  device = "jpeg",
  dpi = "retina"
  )

```

# Variable importance

```{r load var imp files}

regional_native_var_imp <- read.csv(file = file.path(mypath, "slf_regional_native_v3", "regional_native_variable_importance.csv"))

regional_invaded_var_imp <- read.csv(file = file.path(mypath, "slf_regional_invaded_v7", "regional_invaded_variable_importance.csv"))

regional_invaded_asian_var_imp <- read.csv(file = file.path(mypath, "slf_regional_invaded_asian_v2", "regional_invaded_asian_variable_importance.csv"))

```

```{r get base plots}

regional_native_var_imp_plot <- SDMtune::plotVarImp(
  df = regional_native_var_imp
) %>%
  ggplot_build()

# change groups
regional_native_var_imp_plot[["data"]][[1]][["x"]] <- c(1, 4, 2, 3)



regional_invaded_var_imp_plot <- SDMtune::plotVarImp(
  df = regional_invaded_var_imp
) %>%
  ggplot_build()

# change groups
regional_invaded_var_imp_plot[["data"]][[1]][["x"]] <- c(1, 2, 3, 4)



regional_invaded_asian_var_imp_plot <- SDMtune::plotVarImp(
  df = regional_invaded_asian_var_imp
) %>%
  ggplot_build()

# change groups
regional_invaded_asian_var_imp_plot[["data"]][[1]][["x"]] <- c(1, 2, 4, 3)

```

```{r var imp plot}

var_imp_ensemble <- ggplot() +
  # native model data
  geom_col(data = regional_native_var_imp_plot$data[[1]], aes(x = x + 0.2, y = y, fill = "Rn (native)"), color = "black", width = 0.2) +
  # invaded model data
  geom_col(data = regional_invaded_var_imp_plot$data[[1]], aes(x = x, y = y, fill = "Ri.NAmerica"), color = "black", width = 0.2) +
  # invaded_asian model data
  geom_col(data = regional_invaded_asian_var_imp_plot$data[[1]], aes(x = x - 0.2, y = y, fill = "Ri.Asia"), color = "black", width = 0.2) +
  labs(
    title = "Variable Importance for 'regional_ensemble' models",
    x = "",
    y = "Permutation importance"
    ) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4),
    labels = c("bio 2", "bio 12", "bio 11", "bio 15")
  ) +
  scale_y_continuous(labels = scales::percent) +
    # aes
  theme_bw() +
  scale_fill_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "fill"
  ) +
  theme(legend.position = "bottom") +
  coord_flip()

```

```{r save plot}

ggsave(
  var_imp_ensemble, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "Variable_importance_regional_ensemble.jpg"
    ),
  height = 8, 
  width = 8,
  device = "jpeg",
  dpi = "retina"
  )

```

# Add global model to AUC and var imp plots

## ROC

```{r load plotting objects}

global_model <- read_rds(file = file.path(mypath, "slf_global_v3", "global_model.rds"))
global_test <- read_rds(file = file.path(mypath, "slf_global_v3", "global_test.rds"))

ensemble_colors <- c(
  "Rn (native)" = "#4daf4a",
  "Ri.NAmerica" =  "#e41a1c",
  "Ri.Asia" = "#377eb8",
  "global" = "black"
)


```

```{r add global ROC}

global_ROC <- SDMtune::plotROC(
  model = global_model@models[[5]], #pick one because they did not vary too much
  test = global_test
) %>%
  ggplot_build()

```

```{r ROC plot}

ROC_ensemble_global <- ggplot() +
  # global
  geom_line(data = global_ROC$data[[1]], aes(x = x, y = y, color = "global", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # native model data
  geom_line(data = regional_native_ROC$data[[1]], aes(x = x, y = y, color = "Rn (native)", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # invaded model data
  geom_line(data = regional_invaded_ROC$data[[1]], aes(x = x, y = y, color = "Ri.NAmerica", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # invaded_asian model data
  geom_line(data = regional_invaded_asian_ROC$data[[1]], aes(x = x, y = y, color = "Ri.Asia", group = group, linetype = as.factor(group)), linewidth = 0.8) +
  # midpoint line
  geom_abline(slope = 1, linetype = "dashed") +
  # scales
  scale_x_continuous(name = "False positive rate (1 - specificity)", breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  scale_y_continuous(name = "True positive rate (sensitivity)", breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  labs(
    title = "ROC curve (true vs false positive rate) for 'regional_ensemble' and 'global' models"
    ) +
  theme_bw() +
  # aes
  scale_color_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "color"
  ) +
  scale_linetype_manual(
    name = "Data segment",
    values = c("solid", "dotted"),
    labels = c("Test", "Train"),
    guide = guide_legend(reverse = TRUE)
  ) +
  theme(legend.position = "bottom") +
  coord_fixed(ratio = 1)

```

```{r save plot}

ggsave(
  ROC_ensemble_global, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "ROC_plot_regional_ensemble_global.jpg"
    ),
  height = 8, 
  width = 8,
  device = "jpeg",
  dpi = "retina"
  )

```

## var imp plots

```{r load var imp files}

global_var_imp <- read.csv(file = file.path(mypath, "slf_global_v3", "global_variable_importance.csv"))

```

```{r get base plots}

global_var_imp_plot <- SDMtune::plotVarImp(
  df = global_var_imp
) %>%
  ggplot_build()


```

```{r var imp plot}

var_imp_ensemble <- ggplot() +
  # native model data
  geom_col(data = global_var_imp_plot$data[[1]], aes(x = x - 0.4, y = y, fill = "global"), color = "black", width = 0.2) +
  # native model data
  geom_col(data = regional_native_var_imp_plot$data[[1]], aes(x = x - 0.2, y = y, fill = "Rn (native)"), color = "black", width = 0.2) +
  # invaded model data
  geom_col(data = regional_invaded_var_imp_plot$data[[1]], aes(x = x, y = y, fill = "Ri.NAmerica"), color = "black", width = 0.2) +
  # invaded_asian model data
  geom_col(data = regional_invaded_asian_var_imp_plot$data[[1]], aes(x = x + 0.2, y = y, fill = "Ri.Asia"), color = "black", width = 0.2) +
  labs(
    title = "Variable Importance for 'regional_ensemble' and 'global' models",
    x = "",
    y = "Permutation importance"
    ) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4),
    labels = c("bio 2", "bio 12", "bio 11", "bio 15")
  ) +
  scale_y_continuous(labels = scales::percent) +
    # aes
  theme_bw() +
  scale_fill_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "fill"
  ) +
  theme(legend.position = "bottom") +
  coord_flip()

```

```{r save plot}

ggsave(
  var_imp_ensemble, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "Variable_importance_regional_ensemble_global.jpg"
    ),
  height = 8, 
  width = 8,
  device = "jpeg",
  dpi = "retina"
  )

```







# Appendix

I DITCHED THIS

## jackknife and leave-one-out test

```{r jackknife pattern object}

jk_patterns <- c(
  `2` = "stripe",
  `1` = "none"
)

```


```{r import jackknife test outputs}


regional_native_jk <- read.csv(file = file.path(mypath, "slf_regional_native_v3", "regional_native_jackknife_training_testing.csv"))

regional_invaded_jk <- read.csv(file = file.path(mypath, "slf_regional_invaded_v7", "regional_invaded_jackknife_training_testing.csv"))

regional_invaded_asian_jk <- read.csv(file = file.path(mypath, "slf_regional_invaded_asian_v2", "regional_invaded_asian_jackknife_training_testing.csv"))


```


```{r plot training jackknives}

regional_native_jk_train_plot <- SDMtune::plotJk(
  jk = regional_native_jk,
  type = "train"
) %>%
  ggplot_build()

regional_native_jk_train_plot[["data"]][[1]][["group"]] <- c(1, 2, 1, 2, 1, 2, 1, 2)


regional_invaded_jk_train_plot <- SDMtune::plotJk(
  jk = regional_invaded_jk,
  type = "train"
) %>%
  ggplot_build()

regional_invaded_jk_train_plot[["data"]][[1]][["group"]] <- c(1, 2, 1, 2, 1, 2, 1, 2)


regional_invaded_asian_jk_train_plot <- SDMtune::plotJk(
  jk = regional_invaded_asian_jk,
  type = "train"
) %>%
  ggplot_build()

regional_invaded_asian_jk_train_plot[["data"]][[1]][["group"]] <- c(1, 2, 1, 2, 1, 2, 1, 2)


```

```{r plot testing jackknives}

regional_native_jk_test_plot <- SDMtune::plotJk(
  jk = regional_native_jk,
  type = "test"
) %>%
  ggplot_build()

regional_native_jk_test_plot[["data"]][[1]][["group"]] <- c(1, 2, 1, 2, 1, 2, 1, 2)


regional_invaded_jk_test_plot <- SDMtune::plotJk(
  jk = regional_invaded_jk,
  type = "test"
) %>%
  ggplot_build()

regional_invaded_jk_test_plot[["data"]][[1]][["group"]] <- c(1, 2, 1, 2, 1, 2, 1, 2)


regional_invaded_asian_jk_test_plot <- SDMtune::plotJk(
  jk = regional_invaded_asian_jk,
  type = "test"
) %>%
  ggplot_build()

regional_invaded_asian_jk_test_plot[["data"]][[1]][["group"]] <- c(1, 2, 1, 2, 1, 2, 1, 2)


```

```{r jk train plot}

jk_train_ensemble <- ggplot() +
  # native model data
  geom_col_pattern(data = regional_native_jk_train_plot$data[[1]], aes(x = x - 0.1, y = y, fill = "Rn (native)", group = group, pattern = as.factor(group)), pattern_fill = "black", pattern_angle = 45, pattern_density = 0.1, pattern_spacing = 0.025, pattern_key_scale_factor = 0.6, width = 0.1, color = "black") +
  # invaded model data
 # geom_col(data = regional_invaded_jk_train_plot$data[[1]], aes(x = x + 0.1, y = y, fill = "Ri.NAmerica"), color = "black", width = 0.1) +
  # invaded_asian model data
  #geom_col(data = regional_invaded_asian_jk_train_plot$data[[1]], aes(x = x, y = y, fill = "Ri.Asia"), color = "black", width = 0.1) +
  labs(
    title = "Jackknife 'regional_ensemble' models",
    x = "",
    y = "Train AUC"
    ) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4),
    labels = c("bio 2", "bio 12", "bio 11", "bio 15")
  ) +
    # aes
  theme_bw() +
  scale_fill_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "fill",
  ) +
  scale_pattern_manual(
    name = "Data segment",
    values = jk_patterns,
    labels = c("leave-one-out", "with only")
    ) +
  theme(legend.position = "bottom") +
  guides(
    pattern = guide_legend(override.aes = list(fill = "white")),
    fill = guide_legend(override.aes = list(pattern = "none"))
    ) +
  coord_flip() 
  
  
  
  
 geom_bar_pattern(position = position_dodge(preserve = "single"),
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6) + 
  scale_fill_manual(values = colorRampPalette(c("#0066CC","#FFFFFF","#FF8C00"))(4)) +
  scale_pattern_manual(values = c(Nerd = "stripe", NotNerd = "none")) +
  labs(x = "Class", y = "Number of Students", pattern = "Nerd?") + 
  guides(pattern = guide_legend(override.aes = list(fill = "white")),
         fill = guide_legend(override.aes = list(pattern = "none")))

```

