---
title: "Plot AUC curves and variable contribution graphs"
author: "Samuel M. Owens"
contact: "sam.owens@temple.edu"
date: "2024-05-09"
---

THEORY

# Setup

```{r load necesssary packages, echo = FALSE}

# general tools
library(tidyverse)  #data manipulation
library(here) #making directory pathways easier on different instances
here::here() # here::here() starts at the root folder of this package.
library(devtools)

# SDMtune and dependencies
library(SDMtune) # main package used to run SDMs
library(dismo) # package underneath SDMtune
library(rJava) # for running MaxEnt
library(plotROC) # plots ROCs

```

These plots depict the activity of the variables put into the MaxEnt models. I will create a combined figure for the 3 models in the regional_ensemble

```{r set wd}

mypath <- file.path(here::here() %>% 
                       dirname(),
                     "maxent/models")

```

```{r style object}

ensemble_colors <- c(
  "native" = "#4daf4a",
  "invaded" =  "#e41a1c",
  "invaded_asian" = "#377eb8"
)

```

```{r load model objects}

regional_native_model <- read_rds(file = file.path(mypath, "slf_regional_native_v2", "regional_native_model.rds"))

regional_invaded_model <- read_rds(file = file.path(mypath, "slf_regional_invaded_v6", "regional_invaded_model.rds"))

regional_invaded_asian_model <- read_rds(file = file.path(mypath, "slf_regional_invaded_asian_v1", "regional_invaded_asian_model.rds"))

```


*note* the testing datasets were loaded into my globalenv by running the first parts of vignettes 070, 080 and 090.

# ROC regional ensemble

```{r extract marginal plots per model- bio 11}

regional_native_ROC <- SDMtune::plotROC(
  model = regional_native_model,
  test = regional_native_test
) %>%
  ggplot_build()


regional_invaded_ROC <- SDMtune::plotROC(
  model = regional_invaded_model,
  test = regional_invaded_test
) %>%
  ggplot_build()

regional_invaded_asian_ROC <- SDMtune::plotROC(
  model = regional_invaded_asian_model,
  test = regional_invaded_asian_test
) %>%
  ggplot_build()
           

```

```{r ROC plot}

ROC_ensemble <- ggplot() +
  # native model data
  geom_line(data = regional_native_ROC$data[[1]], aes(x = x, y = y, color = "native", group = group, linetype = as.factor(group))) +
  # invaded model data
  geom_line(data = regional_invaded_ROC$data[[1]], aes(x = x, y = y, color = "invaded", group = group, linetype = as.factor(group))) +
  # invaded_asian model data
  geom_line(data = regional_invaded_asian_ROC$data[[1]], aes(x = x, y = y, color = "invaded_asian", group = group, linetype = as.factor(group))) +
  # midpoint line
  geom_abline(slope = 1, linetype = "dashed") +
  # scales
  scale_x_continuous(name = "False positive rate (1 - specificity)", breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  scale_y_continuous(name = "True positive rate (sensitivity)", breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  labs(
    title = "ROC curve (true vs false positive rate) for 'regional_ensemble' models"
    ) +
  theme_bw() +
  # aes
  scale_color_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "color"
  ) +
  scale_linetype_manual(
    name = "Data segment",
    values = c(1, 2),
    labels = c("Test", "Train"),
    guide = guide_legend(reverse = TRUE)
  ) +
  theme(legend.position = "bottom") +
  coord_fixed(ratio = 1)

```

```{r save plot}

ggsave(
  ROC_ensemble, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "ROC_plot_regional_ensemble.jpg"
    ),
  height = 8, 
  width = 8,
  device = "jpeg",
  dpi = "retina"
  )

```

# Variable importance

```{r load var imp files}

regional_native_var_imp <- read.csv(file = file.path(mypath, "slf_regional_native_v2", "regional_native_variable_importance.csv"))

regional_invaded_var_imp <- read.csv(file = file.path(mypath, "slf_regional_invaded_v6", "regional_invaded_variable_importance.csv"))

regional_invaded_asian_var_imp <- read.csv(file = file.path(mypath, "slf_regional_invaded_asian_v1", "regional_invaded_asian_variable_importance.csv"))

```


```{r get base plots}

regional_native_var_imp_plot <- SDMtune::plotVarImp(
  df = regional_native_var_imp
) %>%
  ggplot_build()

# change groups
regional_native_var_imp_plot[["data"]][[1]][["x"]] <- c(1, 4, 2, 3)



regional_invaded_var_imp_plot <- SDMtune::plotVarImp(
  df = regional_invaded_var_imp
) %>%
  ggplot_build()

# change groups
regional_invaded_var_imp_plot[["data"]][[1]][["x"]] <- c(1, 2, 3, 4)



regional_invaded_asian_var_imp_plot <- SDMtune::plotVarImp(
  df = regional_invaded_asian_var_imp
) %>%
  ggplot_build()

# change groups
regional_invaded_asian_var_imp_plot[["data"]][[1]][["x"]] <- c(1, 2, 4, 3)

```

```{r var imp plot}

var_imp_ensemble <- ggplot() +
  # native model data
  geom_col(data = regional_native_var_imp_plot$data[[1]], aes(x = x - 0.2, y = y, fill = "native"), color = "black", width = 0.5) +
  # invaded model data
  geom_col(data = regional_invaded_var_imp_plot$data[[1]], aes(x = x + 0.2, y = y, fill = "invaded"), color = "black", width = 0.5) +
  # invaded_asian model data
  geom_col(data = regional_invaded_asian_var_imp_plot$data[[1]], aes(x = x, y = y, fill = "invaded_asian"), color = "black", width = 0.5) +
  labs(
    title = "Variable Importance for 'regional_ensemble' models",
    x = "",
    y = "Permutation importance"
    ) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4),
    labels = c("bio 2", "bio 12", "bio 11", "bio 15")
  ) +
  scale_y_continuous(labels = scales::percent) +
    # aes
  theme_bw() +
  scale_fill_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "fill"
  ) +
  theme(legend.position = "bottom") +
  coord_flip()

```

```{r save plot}

ggsave(
  var_imp_ensemble, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "Variable_importance_regional_ensemble.jpg"
    ),
  height = 8, 
  width = 8,
  device = "jpeg",
  dpi = "retina"
  )

```

