---
title: "Additional figures"
author: "Samuel M. Owens"
contact: "sam.owens@temple.edu"
format: html
editor: visual
---

I will create additional figures I need for my analysis.

# Setup

```{r load necesssary packages, echo = FALSE}

# general tools
library(tidyverse)  #data manipulation
library(here) #making directory pathways easier on different instances
here::here() # here::here() starts at the root folder of this package.
library(devtools)

# SDMtune and dependencies
library(SDMtune) # main package used to run SDMs
library(dismo) # package underneath SDMtune
library(rJava) # for running MaxEnt
library(plotROC) # plots ROCs

# spatial data handling
library(raster) 
library(terra) 
library(sf)

library(viridis)

```

# Marginal Response plots

These plots depict the activity of the variables put into the MaxEnt models. I will create a combined figure for the 3 models in the regional_ensemble

## Setup

```{r set wd}

mypath <- file.path(here::here() %>% 
                       dirname(),
                     "maxent/models")

```

```{r scatter style object}

ensemble_colors <- c(
  "native" = "#4daf4a",
  "invaded" =  "#e41a1c",
  "invaded_asian" = "#377eb8"
)

marginal_plots_style <- list(
  theme_bw(),
  # labs
  labs(
    title = "Marginal response of 'regional_ensemble' models",
    color = "Model",
    caption = "rug plots indicate presences"
    ),
  ylab("cloglog_output"),
  # aes
  scale_color_manual(
    name = "model",
    values = ensemble_colors,
    aesthetics = "color"
  ),
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)),
  theme(legend.position = "bottom"),
  geom_hline(aes(yintercept = 0), color = "black", linewidth = 0.5) 
)

```


```{r load model objects}

regional_native_model <- read_rds(file = file.path(mypath, "slf_regional_native_v2", "regional_native_model.rds"))

regional_invaded_model <- read_rds(file = file.path(mypath, "slf_regional_invaded_v6", "regional_invaded_model.rds"))

regional_invaded_asian_model <- read_rds(file = file.path(mypath, "slf_regional_invaded_asian_v1", "regional_invaded_asian_model.rds"))

```

## create plots

### Bio 11

```{r extract marginal plots per model- bio 11}

regional_native_marginal_bio11 <- SDMtune::plotResponse(
  model = regional_native_model,
  var = "bio11",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()


regional_invaded_marginal_bio11 <- SDMtune::plotResponse(
  model = regional_invaded_model,
  var = "bio11",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()

regional_invaded_asian_marginal_bio11 <- SDMtune::plotResponse(
  model = regional_invaded_asian_model,
  var = "bio11",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()
           

```

```{r plotting elements}

# peak y trendline object 
bio11_max_activity_values <- c(
  native_bio_11 = regional_native_marginal_bio11$data[[1]][which.max(regional_native_marginal_bio11$data[[1]]$y), ]$x,
  invaded_bio_11 = regional_invaded_marginal_bio11$data[[1]][which.max(regional_invaded_marginal_bio11$data[[1]]$y), ]$x,
  invaded_asian_bio_11 = regional_invaded_asian_marginal_bio11$data[[1]][which.max(regional_invaded_asian_marginal_bio11$data[[1]]$y), ]$x
)

```


```{r combine plots}

bio11_marginal_combined <- ggplot() +
  # native model data
  geom_smooth(data = regional_native_marginal_bio11$data[[1]], aes(x = x, y = y, color = "native"), se = FALSE, method = "gam") +
  # invaded model data
  geom_smooth(data = regional_invaded_marginal_bio11$data[[1]], aes(x = x, y = y, color = "invaded"), se = FALSE, method = "gam") +
  # invaded_asian model data
  geom_smooth(data = regional_invaded_asian_marginal_bio11$data[[1]], aes(x = x, y = y, color = "invaded_asian"), se = FALSE, method = "gam") +
  # plot peak trendline and labels
  # native
  geom_vline(aes(xintercept = bio11_max_activity_values[[1]], color = "native"), linetype = "dashed", linewidth = 0.5) +
  # invaded
  geom_vline(aes(xintercept = bio11_max_activity_values[[2]], color = "invaded"), linetype = "dashed", linewidth = 0.5) +
  # invaded_asian
  geom_vline(aes(xintercept = bio11_max_activity_values[[3]], color = "invaded_asian"), linetype = "dashed", linewidth = 0.5) +
  # plot rug plots
  # native
  geom_rug(aes(x = regional_native_marginal_bio11$data[[2]]$x, color = "native"), sides = "t") +
  # invaded
  geom_rug(aes(x = regional_invaded_marginal_bio11$data[[2]]$x, color = "invaded"), sides = "t", alpha = 0.8) +
  # invaded_asian
  geom_rug(aes(x = regional_invaded_asian_marginal_bio11$data[[2]]$x, color = "invaded_asian"), sides = "t", alpha = 0.6) +
  # default style
  marginal_plots_style +
  # labels
  labs(
    subtitle = "Bio 11 (mean temperature of the coldest quarter)",
    x = "mean temperature of the coldest quarter (C)"
    ) +
  # aesthetics
  xlim(-20, 20) 
  

```

```{r save plot}

ggsave(
  bio11_marginal_combined, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "regional_ensemble_bio11_marginal_resp_curve_cloglog.jpg"
    ),
  height = 8, 
  width = 10,
  device = "jpeg",
  dpi = "retina"
  )

```

### Bio 12

```{r extract marginal plots per model- bio 12}

regional_native_marginal_bio12 <- SDMtune::plotResponse(
  model = regional_native_model,
  var = "bio12",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()


regional_invaded_marginal_bio12 <- SDMtune::plotResponse(
  model = regional_invaded_model,
  var = "bio12",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()

regional_invaded_asian_marginal_bio12 <- SDMtune::plotResponse(
  model = regional_invaded_asian_model,
  var = "bio12",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()
           

```

```{r plotting elements}

# peak y trendline object 
bio12_max_activity_values <- c(
  native_bio_12 = regional_native_marginal_bio12$data[[1]][which.max(regional_native_marginal_bio12$data[[1]]$y), ]$x,
  invaded_bio_12 = regional_invaded_marginal_bio12$data[[1]][which.max(regional_invaded_marginal_bio12$data[[1]]$y), ]$x,
  invaded_asian_bio_12 = regional_invaded_asian_marginal_bio12$data[[1]][which.max(regional_invaded_asian_marginal_bio12$data[[1]]$y), ]$x
)

```


```{r combine plots}

bio12_marginal_combined <- ggplot() +
  # native model data
  geom_smooth(data = regional_native_marginal_bio12$data[[1]], aes(x = x, y = y, color = "native"), se = FALSE, method = "gam") +
  # invaded model data
  geom_smooth(data = regional_invaded_marginal_bio12$data[[1]], aes(x = x, y = y, color = "invaded"), se = FALSE, method = "gam") +
  # invaded_asian model data
  geom_smooth(data = regional_invaded_asian_marginal_bio12$data[[1]], aes(x = x, y = y, color = "invaded_asian"), se = FALSE, method = "gam") +
  # plot peak trendline and labels
  # native
  geom_vline(aes(xintercept = bio12_max_activity_values[[1]], color = "native"), linetype = "dashed", linewidth = 0.5) +
  # invaded
  geom_vline(aes(xintercept = bio12_max_activity_values[[2]], color = "invaded"), linetype = "dashed", linewidth = 0.5) +
  # invaded_asian
  geom_vline(aes(xintercept = bio12_max_activity_values[[3]], color = "invaded_asian"), linetype = "dashed", linewidth = 0.5) +
  # plot rug plots
  # native
  geom_rug(aes(x = regional_native_marginal_bio12$data[[2]]$x, color = "native"), sides = "t") +
  # invaded
  geom_rug(aes(x = regional_invaded_marginal_bio12$data[[2]]$x, color = "invaded"), sides = "t", alpha = 0.8) +
  # invaded_asian
  geom_rug(aes(x = regional_invaded_asian_marginal_bio12$data[[2]]$x, color = "invaded_asian"), sides = "t", alpha = 0.6) +
  # default style
  marginal_plots_style +
  # labels
  labs(
    subtitle = "Bio 12 (Annual Precipitation)",
    x = "annual precipitation (mm)"
    ) +
  # aesthetics
  xlim(0, 3000) 
  

```

```{r save plot}

ggsave(
  bio12_marginal_combined, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "regional_ensemble_bio12_marginal_resp_curve_cloglog.jpg"
    ),
  height = 8, 
  width = 10,
  device = "jpeg",
  dpi = "retina"
  )

```

### Bio 15

```{r extract marginal plots per model- bio 15}

regional_native_marginal_bio15 <- SDMtune::plotResponse(
  model = regional_native_model,
  var = "bio15",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()


regional_invaded_marginal_bio15 <- SDMtune::plotResponse(
  model = regional_invaded_model,
  var = "bio15",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()

regional_invaded_asian_marginal_bio15 <- SDMtune::plotResponse(
  model = regional_invaded_asian_model,
  var = "bio15",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()
           

```

```{r plotting elements}

# peak y trendline object 
bio15_max_activity_values <- c(
  native_bio_15 = regional_native_marginal_bio15$data[[1]][which.max(regional_native_marginal_bio15$data[[1]]$y), ]$x,
  invaded_bio_15 = regional_invaded_marginal_bio15$data[[1]][which.max(regional_invaded_marginal_bio15$data[[1]]$y), ]$x,
  invaded_asian_bio_15 = regional_invaded_asian_marginal_bio15$data[[1]][which.max(regional_invaded_asian_marginal_bio15$data[[1]]$y), ]$x
)

```


```{r combine plots}

bio15_marginal_combined <- ggplot() +
  # native model data
  geom_smooth(data = regional_native_marginal_bio15$data[[1]], aes(x = x, y = y, color = "native"), se = FALSE, method = "gam") +
  # invaded model data
  geom_smooth(data = regional_invaded_marginal_bio15$data[[1]], aes(x = x, y = y, color = "invaded"), se = FALSE, method = "gam") +
  # invaded_asian model data
  geom_smooth(data = regional_invaded_asian_marginal_bio15$data[[1]], aes(x = x, y = y, color = "invaded_asian"), se = FALSE, method = "gam") +
  # plot peak trendline and labels
  # native
  geom_vline(aes(xintercept = bio15_max_activity_values[[1]], color = "native"), linetype = "dashed", linewidth = 0.5) +
  # invaded
  geom_vline(aes(xintercept = bio15_max_activity_values[[2]], color = "invaded"), linetype = "dashed", linewidth = 0.5) +
  # invaded_asian
  geom_vline(aes(xintercept = bio15_max_activity_values[[3]], color = "invaded_asian"), linetype = "dashed", linewidth = 0.5) +
  # plot rug plots
  # native
  geom_rug(aes(x = regional_native_marginal_bio15$data[[2]]$x, color = "native"), sides = "t") +
  # invaded
  geom_rug(aes(x = regional_invaded_marginal_bio15$data[[2]]$x, color = "invaded"), sides = "t", alpha = 0.8) +
  # invaded_asian
  geom_rug(aes(x = regional_invaded_asian_marginal_bio15$data[[2]]$x, color = "invaded_asian"), sides = "t", alpha = 0.6) +
  # default style
  marginal_plots_style +
  # labels
  labs(
    subtitle = "Bio 15 (Precipitation Seasonality, CV)",
    x = "precipitation seasonality (%)"
    ) +
  # aesthetics
  xlim(0, 110) 
  

```

```{r save plot}

ggsave(
  bio15_marginal_combined, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "regional_ensemble_bio15_marginal_resp_curve_cloglog.jpg"
    ),
  height = 8, 
  width = 10,
  device = "jpeg",
  dpi = "retina"
  )

```

### Bio 2

```{r extract marginal plots per model- bio 2}

regional_native_marginal_bio2 <- SDMtune::plotResponse(
  model = regional_native_model,
  var = "bio2",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()


regional_invaded_marginal_bio2 <- SDMtune::plotResponse(
  model = regional_invaded_model,
  var = "bio2",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()

regional_invaded_asian_marginal_bio2 <- SDMtune::plotResponse(
  model = regional_invaded_asian_model,
  var = "bio2",
  type = "cloglog",
  fun = mean,
  only_presence = TRUE,
  marginal = TRUE,
  rug = TRUE
) %>%
  ggplot_build()
           

```

```{r plotting elements}

# peak y trendline object 
bio2_max_activity_values <- c(
  native_bio_2 = regional_native_marginal_bio2$data[[1]][which.max(regional_native_marginal_bio2$data[[1]]$y), ]$x,
  invaded_bio_2 = regional_invaded_marginal_bio2$data[[1]][which.max(regional_invaded_marginal_bio2$data[[1]]$y), ]$x,
  invaded_asian_bio_2 = regional_invaded_asian_marginal_bio2$data[[1]][which.max(regional_invaded_asian_marginal_bio2$data[[1]]$y), ]$x
)

```


```{r combine plots}

bio2_marginal_combined <- ggplot() +
  # native model data
  geom_smooth(data = regional_native_marginal_bio2$data[[1]], aes(x = x, y = y, color = "native"), se = FALSE, method = "gam") +
  # invaded model data
  geom_smooth(data = regional_invaded_marginal_bio2$data[[1]], aes(x = x, y = y, color = "invaded"), se = FALSE, method = "gam") +
  # invaded_asian model data
  geom_smooth(data = regional_invaded_asian_marginal_bio2$data[[1]], aes(x = x, y = y, color = "invaded_asian"), se = FALSE, method = "gam") +
  # plot peak trendline and labels
  # native
  geom_vline(aes(xintercept = bio2_max_activity_values[[1]], color = "native"), linetype = "dashed", linewidth = 0.5) +
  # invaded
  geom_vline(aes(xintercept = bio2_max_activity_values[[2]], color = "invaded"), linetype = "dashed", linewidth = 0.5) +
  # invaded_asian
  geom_vline(aes(xintercept = bio2_max_activity_values[[3]], color = "invaded_asian"), linetype = "dashed", linewidth = 0.5) +
  # plot rug plots
  # native
  geom_rug(aes(x = regional_native_marginal_bio2$data[[2]]$x, color = "native"), sides = "t") +
  # invaded
  geom_rug(aes(x = regional_invaded_marginal_bio2$data[[2]]$x, color = "invaded"), sides = "t", alpha = 0.8) +
  # invaded_asian
  geom_rug(aes(x = regional_invaded_asian_marginal_bio2$data[[2]]$x, color = "invaded_asian"), sides = "t", alpha = 0.6) +
  # default style
  marginal_plots_style +
  # labels
  labs(
    subtitle = "Bio 2 (Mean Diurnal Range)",
    x = "mean diurnal range (C)"
    ) +
  # aesthetics
  xlim(0, 15) 
  

```

```{r save plot}

ggsave(
  bio2_marginal_combined, 
  filename = file.path(
    here::here(), "vignette-outputs", "figures", "regional_ensemble_bio2_marginal_resp_curve_cloglog.jpg"
    ),
  height = 8, 
  width = 10,
  device = "jpeg",
  dpi = "retina"
  )

```


